version: "3.7"
services:
    home-control:
        build: .
        env_file:
            - .env.production
        volumes:
            - ./src/:/usr/src/app/src/
            - /sys/class/gpio/:/sys/class/gpio/
            - /sys/devices/platform/soc/3f200000.gpio:/sys/devices/platform/soc/3f200000.gpio
        restart: always
        expose:
            - 3000

    prometheus:
        image: prom/prometheus:latest
        container_name: monitoring_prometheus
        restart: unless-stopped
        links:
            - home-control:home-control
        volumes:
            - ./prometheus/:/etc/prometheus/
            - ./data/prometheus/data:/prometheus
        # command:
        #     - '-config.file=/etc/prometheus/prometheus.yml'
        #     - '-storage.local.path=/prometheus'
        expose:
            - 9090
        ports:
            - 9090:9090


    grafana:
        image: grafana/grafana:latest
        container_name: monitoring_grafana
        restart: unless-stopped
        links:
            - prometheus:prometheus
        volumes:
            - ./data/grafana:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORD
            - GF_USERS_ALLOW_SIGN_UP=false
            - GF_SERVER_DOMAIN=myrul.com
            - GF_SMTP_ENABLED=true
            - GF_SMTP_HOST=smtp.gmail.com:587
            - GF_SMTP_USER=myadrress@gmail.com
            - GF_SMTP_PASSWORD=mypassword
            - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
        expose:
            - 3000
        ports:
            - 3000:3000



